import React, { useState } from "react";
import { Link } from "react-router-dom";
import "./ReadingTest.scss";

const ReadingTest = () => {
  const [activeTab, setActiveTab] = useState("content");
  const [selectedAnswer, setSelectedAnswer] = useState(null);

  return (
    <div className="readingpage">
      <div className="reading">
        <div className="reading__header">
          <div className="container">
            <div className="reading__wrapper">
              <Link to="/tests">
                <button className="reading__btn">
                  <img src="./arrow1.svg" alt="back" />
                </button>
              </Link>
              <h2 className="reading__title">Reading Test</h2>
              <div className="reading__time">30:00</div>
            </div>
          </div>
        </div>

        <div className="container">
          <div className="reading__nav">
            <button
              className={activeTab === "content" ? "active" : ""}
              onClick={() => setActiveTab("content")}
            >
              Parts
            </button>
            <button
              className={activeTab === "questions" ? "active" : ""}
              onClick={() => setActiveTab("questions")}
            >
              Questions
            </button>
          </div>

          {activeTab === "content" && (
            <div className="reading__contents">
              <div className="content-section">
                <input
                  type="checkbox"
                  id="text123"
                  className="content-toggle"
                />
                <label htmlFor="text123" className="content-header">
                  <h2>Reading passage 1 (practice test) - Electroreception</h2>
                  <span className="toggle-icon">⯆</span>
                </label>
                <div className="content-body">
                  <p>
                    <b>A.</b>
                    Open your eyes in sea water and it is difficult to see much
                    more than a murky, bleary green colour. Sounds, too, are
                    garbled and difficult to comprehend. Without specialised
                    equipment humans would be lost in these deep sea habitats,
                    so how do fish make it seem so easy? Much of this is due to
                    a biological phenomenon known as electroreception – the
                    ability to perceive and act upon electrical stimuli as part
                    of the overall senses. This ability is only found in aquatic
                    or amphibious species because water is an efficient
                    conductor of electricity.
                  </p>
                  <p>
                    <b>B.</b> Electroreception comes in two variants. While all
                    animals (including humans) generate electric signals,
                    because they are emitted by the nervous system, some animals
                    have the ability – known as passive electroreception – to
                    receive and decode electric signals generated by other
                    animals in order to sense their location.
                  </p>
                  <p>
                    <b>C.</b> Open your eyes in sea water and it is difficult to
                    see much more than a murky, bleary green colour. Sounds,
                    too, are garbled and difficult to comprehend. Without
                    specialised equipment humans would be lost in these deep sea
                    habitats, so how do fish make it seem so easy? Much of this
                    is due to a biological phenomenon known as electroreception
                    – the ability to perceive and act upon electrical stimuli as
                    part of the overall senses. This ability is only found in
                    aquatic or amphibious species because water is an efficient
                    conductor of electricity.
                  </p>
                </div>
              </div>
            </div>
          )}

          {activeTab === "questions" && (
            <div className="reading__questions">
              <div className="reading__question">
                <h4>Question 1 / 40</h4>
                <p>Which paragraph contains the following information?</p>
                <h3>How electroreception can be used to help fish reproduce</h3>
              </div>

              <div className="reading__answer">
                {["A", "B", "C"].map((option) => (
                  <label key={option} htmlFor={`answer-${option}`}>
                    {option}
                    <input
                      type="radio"
                      name="answer"
                      id={`answer-${option}`}
                      checked={selectedAnswer === option}
                      onChange={() => setSelectedAnswer(option)}
                    />
                  </label>
                ))}
              </div>

              <div className="reading__test-bottom">
                <Link to="/tests/reading/start">
                  <button className="reading__button-1">
                    <img src="./arrow1.svg" alt="previous" />
                  </button>
                </Link>

                <Link to="/tests/reading/start" className="reading__btn2">
                  <button
                    className="reading__button-2"
                    disabled={!selectedAnswer}
                  >
                    Confirm
                  </button>
                </Link>

                <Link to="/tests/reading/start">
                  <button className="reading__button-3">
                    <img src="./arrow1.svg" alt="next" />
                  </button>
                </Link>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReadingTest;
