import React, { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import "./SpeakingTest.scss";
import { BiSolidMicrophone } from "react-icons/bi";

const SpeakingTest = () => {
    const [activeTab, setActiveTab] = useState("content");
    const [isRecording, setIsRecording] = useState(false);
    const [audioBlob, setAudioBlob] = useState(null);
    const [time, setTime] = useState(0);

    const mediaRecorderRef = useRef(null);
    const chunksRef = useRef([]);
    const timerRef = useRef(null);

    const formatTime = (sec) => {
        const m = String(Math.floor(sec / 60)).padStart(2, "0");
        const s = String(sec % 60).padStart(2, "0");
        return `${m}:${s}`;
    };

    const startRecording = async () => {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });

        const mediaRecorder = new MediaRecorder(stream);
        mediaRecorderRef.current = mediaRecorder;
        chunksRef.current = [];

        mediaRecorder.ondataavailable = (e) => {
            chunksRef.current.push(e.data);
        };

        mediaRecorder.onstop = () => {
            const blob = new Blob(chunksRef.current, { type: "audio/webm" });
            setAudioBlob(blob);

            mediaRecorder.stream.getTracks().forEach(track => track.stop());
        };

        mediaRecorder.start();
        setIsRecording(true);
        setTime(0);

        timerRef.current = setInterval(() => {
            setTime(t => t + 1);
        }, 1000);
    };

    const stopRecording = () => {
        mediaRecorderRef.current.stop();
        clearInterval(timerRef.current);
        setIsRecording(false);
    };

    useEffect(() => {
        return () => clearInterval(timerRef.current);
    }, []);

    return (
        <div className="speakingpage">
            <div className="speaking">
                <div className="speaking__header">
                    <div className="container">
                        <div className="speaking__wrapper">
                            <Link to="/tests">
                                <button className="speaking__btn">
                                    <img src="/arrow1.svg" alt="back" />
                                </button>
                            </Link>

                            <h2>Speaking Test</h2>
                            <div className="speaking__time">30:00</div>
                        </div>
                    </div>
                </div>

                <div className="container">
                    <div className="speaking__nav">
                        <button
                            className={activeTab === "content" ? "active" : ""}
                            onClick={() => setActiveTab("content")}
                        >
                            Parts
                        </button>
                        <button
                            className={activeTab === "questions" ? "active" : ""}
                            onClick={() => setActiveTab("questions")}
                        >
                            Questions
                        </button>
                    </div>

                    {activeTab === "content" && (
                        <div className="speaking__contents">
                            <input type="checkbox" id="text123" className="content-toggle" />
                            <label htmlFor="text123" className="content-header">
                                <h2>Speaking passage 1 (practice test)</h2>
                                <span className="toggle-icon">⯆</span>
                            </label>
                            <div className="content-body">
                                <p> <b>A.</b> Open your eyes in sea water and it is difficult to see much more than a murky, bleary green colour. Sounds, too, are garbled and difficult to comprehend. Without specialised equipment humans would be lost in these deep sea habitats, so how do fish make it seem so easy? Much of this is due to a biological phenomenon known as electroreception – the ability to perceive and act upon electrical stimuli as part of the overall senses. This ability is only found in aquatic or amphibious species because water is an efficient conductor of electricity. </p>
                                <p> <b>B.</b> Electroreception comes in two variants. While all animals (including humans) generate electric signals, because they are emitted by the nervous system, some animals have the ability – known as passive electroreception – to receive and decode electric signals generated by other animals in order to sense their location. </p>
                                <p> <b>C.</b> Open your eyes in sea water and it is difficult to see much more than a murky, bleary green colour. Sounds, too, are garbled and difficult to comprehend. Without specialised equipment humans would be lost in these deep sea habitats, so how do fish make it seem so easy? Much of this is due to a biological phenomenon known as electroreception – the ability to perceive and act upon electrical stimuli as part of the overall senses. This ability is only found in aquatic or amphibious species because water is an efficient conductor of electricity. </p>
                            </div>
                        </div>
                    )}

                    {/* QUESTIONS */}
                    {activeTab === "questions" && (
                        <div className="speaking__questions">
                            <div className="speaking__question">
                                <h4>Question 1 / 40</h4>
                                <p>Your home town or village</p>
                                <h3>What kind of place is it?</h3>
                            </div>

                            {/* AUDIO BLOCK */}
                            <div
                                className="speaking__answer"
                                onClick={!isRecording ? startRecording : undefined}
                                style={{ cursor: "pointer", background: "#fff" }}
                            >
                                {!isRecording ? (
                                    <div className="speaking-test">
                                        <BiSolidMicrophone className="speaking-icon" />
                                        <h3>Press to record the answer</h3>
                                        <p>You should spend 1-2 minutes on this
                                            part of the test.</p>
                                    </div>
                                ) : (
                                    <div className="speaking-button">
                                        <h3>{formatTime(time)}</h3>
                                        <button onClick={stopRecording}>Stop</button>
                                    </div>
                                )}
                            </div>
                            <div className="speaking__test-bottom">
                                <button
                                    className="speaking__button-2"
                                    disabled={!audioBlob}
                                >
                                    Confirm
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default SpeakingTest;
